FROM python:3.9
WORKDIR /app

RUN apt-get update

COPY dorflutter-cdn/. .
RUN pip install -r ./requirements.txt
ENV PYTHONUNBUFFERED=0
EXPOSE 4000
CMD ["gunicorn", "-b", ":4000", "app:application", "-k", "gevent"]
