version: "2"
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot1
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api1
    depends_on:
      - db
    volumes:
      - ./dorflutter-server:/app
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client1
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./client-react:/app
      - /app/node_modules
  db:
    image: mariadb:10.6.2
    container_name: mysql1
    expose:
      - "3306"
    environment:
      # MYSQL_DATABASE: scrimdor
      MYSQL_ROOT_PASSWORD: backstart
      TZ: Asia/Seoul
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - ./dorflutter-database/data:/var/lib/mysql
      - ./dorflutter-database/conf:/etc/mysql/conf.d/my.cnf
  mongo:
    image: mongo:5.0.3
    container_name: mongo1
    environment:
        MONGO_INITDB_ROOT_USERNAME: dorflutter
        MONGO_INITDB_ROOT_PASSWORD: backstart
        MONGO_INITDB_DATABASE: dorflutter
    expose:
      - "27017"
    volumes: 
      - /mongo_data/db:/data/db
  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    container_name: chat1
    ports:
      - "9000:9000"
    volumes:
      - ./dorflutter-chat-server:/app
      - /app/node_modules
  cdn:
    build:
      context: .
      dockerfile: Dockerfile.cdn
    container_name: cdn1
    hostname: dorflutter-cnd
    volumes:
      - ./dorflutter-cdn:/app